- name: copy MetalLB manifest
  become: yes
  template:
    src: metallb-native.yaml
    dest: /etc/metallb-native.yaml

- name: copy MetalLB config
  become: yes
  template:
    src: metallb-config.yaml
    dest: /etc/metallb-config.yaml

- name: install MetalLB
  become: yes
  command: kubectl apply -f /etc/metallb-native.yaml --kubeconfig=/etc/kubernetes/admin.conf

# TODO: need better logic. Applying the metallb config fails when called immediately after installation
- name: Sleep for 90s
  ansible.builtin.wait_for:
    timeout: 90
  delegate_to: localhost

- name: install MetalLB config
  become: yes
  command: kubectl apply -f /etc/metallb-config.yaml --kubeconfig=/etc/kubernetes/admin.conf
