- name: copy MetalLB config
  become: true
  template:
    src: metallb-config.yaml
    dest: /etc/metallb-config.yaml

- name: add MetalLB helm repo
  become: true
  kubernetes.core.helm_repository:
    name: metallb
    repo_url: https://metallb.github.io/metallb

- name: deploy MetalLB
  become: true
  kubernetes.core.helm:
    name: metallb
    chart_ref: metallb/metallb
    release_namespace: metallb-system
    create_namespace: true
    kubeconfig: /etc/kubernetes/admin.conf
    wait: true
    values_files:
      - "/etc/metallb-config.yaml"

- name: install MetalLB config
  become: true
  command: kubectl apply -f /etc/metallb-config.yaml --kubeconfig=/etc/kubernetes/admin.conf
