- name: copy prod-cluster-issuer config
  become: true
  template:
    src: prod-cluster-issuer.yaml
    dest: /etc/prod-cluster-issuer.yaml

- name: copy staging-cluster-issuer config
  become: true
  template:
    src: staging-cluster-issuer.yaml
    dest: /etc/staging-cluster-issuer.yaml

- name: copy prod-certificate config
  become: true
  template:
    src: prod-certificate.yaml
    dest: /etc/prod-certificate.yaml

- name: copy staging-certificate config
  become: true
  template:
    src: staging-certificate.yaml
    dest: /etc/staging-certificate.yaml

- name: add jetstack helm repo
  become: true
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: installing cert-manager
  become: true
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: true
    set_values:
      - value: installCRDs=true
      - value: clusterResourceNamespace=cert-manager
      - value: extraArgs={--dns01-recursive-nameservers-only,--dns01-recursive-nameservers=8.8.8.8:53\,1.1.1.1:53}
    kubeconfig: /etc/kubernetes/admin.conf

- name: applying staging issuer config
  become: true
  command: kubectl apply -f /etc/staging-cluster-issuer.yaml --kubeconfig=/etc/kubernetes/admin.conf

- name: applying prod issuer config
  become: true
  command: kubectl apply -f /etc/prod-cluster-issuer.yaml --kubeconfig=/etc/kubernetes/admin.conf

- name: applying staging certificate
  become: true
  command: kubectl apply -f /etc/staging-certificate.yaml --kubeconfig=/etc/kubernetes/admin.conf

- name: applying prod certificate
  become: true
  command: kubectl apply -f /etc/prod-certificate.yaml --kubeconfig=/etc/kubernetes/admin.conf
