- name: add istio helm repo
  become: true
  kubernetes.core.helm_repository:
    name: istio
    repo_url: https://istio-release.storage.googleapis.com/charts

- name: deploy istio base
  become: true
  kubernetes.core.helm:
    name: istio-base
    chart_ref: istio/base
    release_namespace: istio-system
    create_namespace: true
    kubeconfig: /etc/kubernetes/admin.conf

- name: deploy istiod
  become: true
  kubernetes.core.helm:
    name: istiod
    chart_ref: istio/istiod
    release_namespace: istio-system
    wait: true
    kubeconfig: /etc/kubernetes/admin.conf

- name: deploy istio-ingressgateway
  become: true
  kubernetes.core.helm:
    name: istio-ingressgateway
    chart_ref: istio/gateway
    release_namespace: ingress
    create_namespace: true
    wait: true
    kubeconfig: /etc/kubernetes/admin.conf
