apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ letsencrypt.name }}-cert-prod"
  namespace: istio-system
spec:
  secretName: "{{ letsencrypt.name}}-cert-prod"
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - "*.wongway.io"
    - "*.k8s.wongway.io"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
